exports.bugs = [
  "ants",
  "aphids/greenfly",
  "asian paper wasp",
  "assassin bug",
  "australian bag moth",
  "avondale spider",
  "backswimmer",
  "bamboo moth",
  "banana moth",
  "banded tunnelweb spider",
  "bed bug",
  "black cockroach",
  "black tunnelweb spider",
  "black-headed jumping spider",
  "blister caused by lax beetle",
  "blowflies",
  "blue moon butterfly",
  "booklice/psocids",
  "bronze beetle",
  "brown garden snail",
  "brown house moth",
  "bumble bees",
  "burnished brass moth",
  "burnt pine longhorn",
  "cabbage tree caterpillar",
  "cabbage tree moth",
  "cabbage white caterpillar",
  "carpet beetle",
  "caterpillar of bamboo moth",
  "caterpillar of cinnabar moth",
  "caterpillar of north island lichen moth",
  "cattle tick",
  "cave weta",
  "chorus cicada",
  "cicada nymph",
  "cinnabar moth",
  "click beetle",
  "clothes moth",
  "codling moth",
  "common bag moth",
  "common blue butterfly",
  "copper butterfly",
  "crane fly/daddy long legs",
  "cricket",
  "daddy longlegs spider",
  "damselfly",
  "desjardin's beetle",
  "dew-drop spider",
  "dried fruit moth",
  "dried fruit moth caterpillar",
  "drugstore beetle",
  "earwig",
  "eucalypt longhorn beetle",
  "european earwig",
  "false katipo spider",
  "field grasshopper",
  "flatworms",
  "flax looper caterpillar",
  "flax notch caterpillar",
  "fleas",
  "flower longhorn beetle",
  "garden orbweb spider",
  "garden slug",
  "garden soldier fly",
  "german cockroach",
  "german wasp",
  "giant dragonfly",
  "giant ichneumonid",
  "giraffe weevil",
  "gisborne cockroach",
  "golden orbweb spider",
  "golden orbweb spider eggsac",
  "grass grub",
  "grass moths",
  "green looper caterpillar",
  "green planthopper",
  "green spangled moth",
  "green stonefly",
  "green vegetable bug",
  "green vegetable bug",
  "grey house spider",
  "guava moth",
  "gum emperor moth",
  "gum emperor moth pupa",
  "gum leaf skeletoniser",
  "gum leaf skeletoniser caterpillar",
  "harvestman",
  "head louse",
  "hibiscus beetle",
  "hide beetle",
  "honey bee",
  "hoppers or amphipods",
  "horizontal orbweb spider",
  "house borer",
  "house centipede",
  "house fly",
  "house fly larvae",
  "huhu beetle",
  "huhu beetle pupa",
  "huhu grub",
  "indian meal moth",
  "katipo spider",
  "katydid",
  "kawakawa looper",
  "kowhai moth",
  "kowhai moth caterpillar",
  "kumara moth",
  "kumara moth caterpillar",
  "kumara moth pupa",
  "ladybird",
  "ladybird larva with wax excretions",
  "large centipede",
  "large white butterfly caterpillar",
  "leafroller caterpillar",
  "leech",
  "lemon tree borer",
  "lesser housefly",
  "lesser wanderer",
  "lesser wanderer caterpillar",
  "light brown apple moth, leafroller caterpillar",
  "locust",
  "longhorn beetles",
  "maggots",
  "magpie moth",
  "mason wasp",
  "mealybug",
  "mealybug ladybird",
  "mercury island tusked weta",
  "metallic green rove beetle",
  "millipedes",
  "mites",
  "mole cricket",
  "monarch butterfly",
  "monarch caterpillar",
  "mosquito",
  "mosquito larvae",
  "mosquito pupa",
  "native bush cockroach",
  "new zealand grasshopper",
  "new zealand praying mantis",
  "new zealand praying mantis eggcase",
  "north island lichen moth",
  "nurseryweb spider",
  "orange ichneumonid wasp",
  "outhouse fly",
  "owl moth caterpillar",
  "owl moth or peacock moth",
  "painted apple moth",
  "painted apple moth caterpillar",
  "painted lady butterfly",
  "passionvine hopper",
  "pasture wireworm",
  "peripatus",
  "plume moths",
  "pseudoscorpion",
  "psyllids",
  "pupa of bamboo moth",
  "puriri moth",
  "puriri moth caterpillar",
  "rattailed maggot",
  "red admiral",
  "red admiral caterpillar",
  "red admiral pupa",
  "rice weevil",
  "sandflies",
  "sandfly bites",
  "scarab beetles",
  "sheetweb spider",
  "silver y moth",
  "silverfish",
  "slater spider",
  "slaters",
  "small green long-legged fly",
  "small land snails",
  "solitary wasp",
  "south african praying mantis",
  "soybean looper",
  "spider hunting wasps",
  "spotted lax beetle",
  "springtails",
  "square ended crab spider",
  "stick insects",
  "striped lax beetle",
  "swan plant seed bug",
  "swift ground spider",
  "tasmanian paper wasp",
  "termites",
  "threelined hoverfly",
  "thrips",
  "tiger beetle",
  "tomato fruitworm",
  "tomato fruitworm moth",
  "tortoise beetle",
  "tree weta",
  "tropical armyworm",
  "tropical armyworm moth",
  "twospined spider",
  "vagrant spider",
  "variegated longhorn",
  "vegetable weevil",
  "veined slug",
  "vinegar flies",
  "wasp workings",
  "water boatman",
  "white butterfly",
  "white spotted tussock moth",
  "white spotted tussock moth caterpillar",
  "whitefly",
  "whitespotted ichneumonid",
  "whitetailed spider",
  "winged weta",
  "wolf spider",
  "wood wasp",
  "wool carder bee",
  "woolly bear caterpillar",
  "worms",
  "yellow admiral",
  "yellow admiral caterpillar",
  "yellow cellar slug",
]
